# Generated by Django 4.1 on 2025-09-16 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("places", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="place",
            name="url",
        ),
        migrations.AddField(
            model_name="place",
            name="city",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="place",
            name="description",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="place",
            name="facility_id",
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.AddField(
            model_name="place",
            name="state",
            field=models.CharField(blank=True, max_length=2),
        ),
        migrations.AddField(
            model_name="place",
            name="zip_code",
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name="place",
            name="address",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="place",
            name="category",
            field=models.CharField(default="Hospital", max_length=100),
        ),
        migrations.AlterField(
            model_name="place",
            name="name",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="place",
            name="slug",
            field=models.SlugField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name="place",
            name="tags",
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
